import React from "react";
import { Metadata } from "next";
import ClientLayout from "./ClientLayout";
import { UserProvider } from "./context/UserContext";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";

// Define metadata (server-side)
export const metadata: Metadata = {
  title: "Bookwyse",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en" dir="ltr">
    <body>
      <UserProvider>
        <ClientLayout>
          <AntdRegistry>{children}</AntdRegistry>
        </ClientLayout>
      </UserProvider>
    </body>
  </html>
);

export default RootLayout;
